export enum OrderStatus {
  IS_NOT_ACCEPTED = 'IS_NOT_ACCEPTED',
  IS_NOT_DELIVERED = 'IS_NOT_DELIVERED',
  IS_DELIVERING = 'IS_DELIVERING',
  IS_DELIVERED = 'IS_DELIVERED',
  IS_CANCELED = 'IS_CANCELED',
  IS_PAID = 'IS_PAID',
  IS_REFUND = 'IS_REFUND',
}
